### ISSUE TITLE
Review of fix for issue 209

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#272]
https://github.com/bettercap/bettercap/commit/1f8e97d91fbb67570c5d44e1c5c0442e497d7d09 was intended to fix issue https://github.com/bettercap/bettercap/issues/209

What if we set `res.Body = ""`?

Wouldn't the `WasModified()` function in **modules/http_proxy_js_response.go** return `false` even if we want to serve an empty response body?

https://github.com/bettercap/bettercap/blob/cfe5f9f76b764efb6f698c02966ae954b0bcdac9/modules/http_proxy_js_response.go#L70

**Comment by evilsocket** [comment]
Mmmm suggestions for a clean approach?

**Comment by yungtravla** [comment]
I think it was fine the way it was: if we want to access a body, we must first read it with `req.ReadBody()` and `res.ReadBody()`.

**Comment by evilsocket** [comment]
yeah but what about `res.Body = "something"` ?

**Comment by yungtravla** [comment]
You mean doing that on a request?

**Comment by yungtravla** [comment]
Oh I see what you mean, maybe we should only use the `bodyRead` boolean (and drop the `WasModified()` function) in order to create a new proxy response?

**Comment by yungtravla** [comment]
That way if we do:

```javascript
function onRequest(req, res) {
}
```

**Comment by evilsocket** [comment]
nope, i don't like, otherwise i would have added getters and setters for everything already :D i need to think a better way, will let you know

**Comment by yungtravla** [comment]
Ok :+1:

**Comment by yungtravla** [comment]
What about rather than having a `bodyRead` bool in the `JSResponse` struct, we could have a `spoofed` bool, so whenever things like `res.Status = 404` are called in the `onRequest()` function, we serve the spoofed response instead of the proxied one?

**Comment by yungtravla** [comment]
And if the `onResponse()` function was modified, we still proxy the response for logging purposes.

**Comment by yungtravla** [comment]
Looking deeper into the code I realize that these things are already the case. The problem is that a new JSResponse struct already has the `Body` param set as an empty string, which could be either proxied or spoofed.

Maybe we can find a way to set the default `Body` param as false, and later on replace it with a set value?

**Comment by evilsocket** [comment]
so? not sure what to do with this issue :/

**Comment by evilsocket** [comment]
thinking about this over and over, we basically have two options (unless we don't want to mess with reflection to see if and how the object changed, but i don't event know if that's possible, will research):

1. We forbid direct access to the fields and implement every single getter and setter (both of the request and response for consistency).
2. We only implement a `ClearBody` method that will set the Body to "" but still signaling (somehow) the object changed.

I vote for 2 ...

**Comment by yungtravla** [comment]
Me too :smile: 

```javascript
res.ToResponse(req)
req.ToRequest()
```

These functions seem to only be of use in other Go functions, but it is part of the JS bindings. Right now it tries to return a `http.Request` or `http.Response` (instead of an object) in the JS interpreter.

What if we enable these inside proxy scripts?

And if we can also create new packets, for example:

**http_proxy_js_request.go**
```javascript
func Request(j *JSRequest) {
  // Check if j is missing required params
  // Return j
}
```

**http_proxy_js_response.go**
```javascript
func Response(j *JSResponse) {
  // Create goproxy response with values from j
  // Return j
}
```

We can then detect a truly empty `res` parameter in the `onRequest()` call.
If it's not empty (it has at least a status code) then we serve it, otherwise we proxy the response.

Because sending requests is restricted to Golang, there are some limitations for the JS proxy scripts. If we can do this in JS, it could allow for more proxy modules, for example: 

**Bypass HTTPS redirect loop**
```javascript
function onResponse(req, res) {
  if (res.Status == 301 || res.Status == 302) {
    location = res.GetHeader("Location", "")
    if ( location.match(/https:\/\//i) ) {
      ssl_req        = req
      ssl_req.Scheme = "https"

      ssl_res = new Response({})
      ssl_res = ssl_res.ToResponse(ssl_req)
      // This could be simplified to:
      //ssl_res = toResponse(ssl_req)
    }
  }
}
```

**Serve empty response without proxying**
```javascript
function onRequest(req, res) {
  res = new Response({
    "Status":  200,
    "Headers": {},
    "Body":    ""
  })
}
```

We can then reflect on the type of the `res` param returned by the `onRequest()` call, and if it's a valid `JSResponse` then we serve it, if it's `false`, we proxy it.

Thoughts?

**Comment by evilsocket** [comment]
man, this issue is just for `Body = ""`, how this new function is related? i'm getting confused

**Comment by yungtravla** [comment]
Basically i'm saying what you said here

> mess with reflection to see if and how the object changed

But instead of just being able to show that the object changed, we make the object in the js proxy script, that way the proxy module always knows when we want to serve a handcrafted packet or not, and it would also allow us to fetch multiple responses before serving a request.

**Comment by evilsocket** [comment]
i don't know, i don't like the idea of breaking backward compatibility just because of `Body = ""` ... i say we should stop changing the JS api :)

**Comment by yungtravla** [comment]
So we leave this `res.Body = ""` issue?

**Comment by yungtravla** [comment]
Oh just saw https://github.com/bettercap/bettercap/commit/f48feddd008ec3bb3bb404a6d64dab78a3688a3a

**Comment by yungtravla** [comment]
Ok, so it wouldn't be smart to send off multiple requests asynchronously, is there no way to do it synchronous? Because I feel like the problem of `res.Body = ""` being ignored is still the case.

**Comment by evilsocket** [comment]
Man, reading your initial report, the problem is that if we set Body to an empty string, the response is not detected as changed ... now it is, if using `ClearBody` as we both already agreed about. 

Not sure how this is strictly related to performing requests from JS modules, let's not mix topics in github issues ... one problem, one fix.

**Comment by yungtravla** [comment]
Yeah, the issue I began is not fixed.

> What if we set res.Body = ""?
> 
> Wouldn't the WasModified() function in modules/http_proxy_js_response.go return false even if we want to serve an empty response body?

This still happens...

**Comment by evilsocket** [comment]
yes, because if you want to clear the body, you have to use `ClearBody` as, again, we both agreed:

![agree](https://user-images.githubusercontent.com/86922/39990510-04f4ffb2-576d-11e8-8358-27484b0ba3c0.png)

**Comment by yungtravla** [comment]
"Me too" was in response to

>thinking about this over and over

Might not have been clear, but the issue remains.

**Comment by evilsocket** [comment]
The issue is "having the ability to clear the body", which is solved with `ClearBody` from my pov. I don't like the idea of creating the whole response or request object inside the javascript itself as it leaves too much freedom to the user (we should validate every single `key => value` being set in the object) ... that was the workaround to overcome this problem, which was solved in a easier and cleaner way ...

**Comment by evilsocket** [comment]
think how many (wrong) ways the user could create that response object from a javascript object ... and we should handle all of them ... nope :D

**Comment by yungtravla** [comment]
`res.ClearBody()` doesn't solve the whole issue but it does allow us to set an empty response body without having to do `res.ReadBody()` or change anything else about the response. 
`res.Body = ""` is still being seen as an unchanged response at this stage though.

I suppose it would require more parsing, but I do think it makes sense to mirror as much http stuff in the JS api as we can :)

**Comment by evilsocket** [comment]
> res.Body = "" is still being seen as an unchanged response at this stage though.

Yes, as, for instance:

> res.IamAfieldThatdoesNotExist = ""

would work, where "work" = won't throw errors but won't have any effect at all ... since the only way for us to handle that would be entirely wrapping the object, but that'd lead to a bad design.

Since an API has been created to do what `res.Body = ""` was supposed to be doing, *functionally* the issue has been solved.

**Comment by yungtravla** [comment]
True, but `res.Body` does exist, and I don't see why `res.Body = ""` should not do the exact same as `res.ClearBody()`.

Plus, having to do `res.ClearBody()` in `onRequest()` just to serve an empty response body doesn't really make sense to me, it sounds more like a function you'd call in `onResponse()` to clear the proxied body.

**Comment by yungtravla** [comment]
But do you see my point?

`res.Body = ""` will effectively wipe the body in the `onRequest()` call (which is already empty to begin with), then it will ignore the fact that we said the response body should be empty, proxy it, and then serve the proxied response. This requires you to download every response even if you weren't gonna serve it anyway.

`res.ClearBody()` does exactly the same except it also states that the body was set to empty with an additional bool to avoid unwanted proxying.

Doing `res.ClearBody()` is no different than doing:

```javascript
res.ReadBody()
res.Body = ""
```

**Comment by evilsocket** [comment]
yes i see your point but i think it's not worth overcomplicating things since now there's an API for that purpose ... `res.Body = ""` is simply something we do not support.
