### ISSUE TITLE
Warning msg: Could not detect gateway

### ISSUE THREAD

**Issue by mgp25** [bettercap/bettercap#357]
- [x] Read the Readme
- [x] Using latest stable version
- [x] Searched in issues. Related issues:
	- #304
	- #355

### Description

For some reason, in any command, I get this warning message at the beginning:

`[01:38:22] [sys.log] [war] Could not detect gateway.`

So far _Bettercap_ run flawlessly in most of its commands, however when I run specific ones like:

`sudo bettercap -caplet http-req-dump.cap -eval "set arp.spoof.targets 192.168.1.121"`

It doesn't seems to be performing the attack. I might be wrong here, but just trying to put things together, and I think it could be related somehow to the warning message. I found this issue (#355), where the user experience the same thing. I am not seeing any traffic at all.

> Full debug output running the caplet annexed at the end

I have also tried passing the `-iface` argument but getting the same results.

`sudo bettercap -iface en0`

As far as I know, it should get the gateway automatically from the interface.

I apologize if everything posted here is correct, I was just wondering why that warning message was appearing.

Regards

### Enviroment

- **Bettercap version:** v2.10 (Stable release)
- **OS version and architecture:** macOS Mojave 10.14 / x86_64
- **Command line arguments:**

```
sudo bettercap
```

Happens with every command.

**Full debug output:**

```
mgp25@mbp:~/desktop$ sudo bettercap --debug
bettercap v2.10 (type 'help' for a list of commands)

[01:38:22] [sys.log] [war] Could not detect gateway.
[01:38:22] [session.started] {session.started 2018-10-11 01:38:22.146613 +0200 CEST m=+0.102018648 <nil>}
[01:38:22] [mod.started] net.recon
[01:38:22] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.122  » [01:38:22] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
192.168.1.0/24 > 192.168.1.122  » [01:38:22] [endpoint.new] endpoint 192.168.1.83 detected as 14:5a:05:xx:xx:xx (Apple, Inc.).
192.168.1.0/24 > 192.168.1.122  » [01:38:22] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
192.168.1.0/24 > 192.168.1.122  »
```

**Actual behavior:**

`[01:38:22] [sys.log] [war] Could not detect gateway.`

#### Full debug output running the caplet

Notice the warning message in this one too:

`[01:51:56] [sys.log] [war] Could not detect gateway.`

```
mgp25@mbp:~/desktop$ sudo bettercap --debug -caplet http-req-dump.cap -eval "set arp.spoof.targets 192.168.1.121"
bettercap v2.10 (type 'help' for a list of commands)

[01:51:56] [sys.log] [war] Could not detect gateway.
[01:51:56] [session.started] {session.started 2018-10-11 01:51:56.090581 +0200 CEST m=+0.105843198 <nil>}
[01:51:56] [sys.log] [dbg] Throttling packets of 10 ms.
[01:51:56] [mod.started] net.recon
[01:51:56] [mod.started] net.probe
[01:51:56] [mod.started] net.probe
[01:51:56] [sys.log] [dbg] sent 88 bytes of MDNS probe
[01:51:56] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
[01:51:56] [endpoint.new] endpoint 192.168.1.55 detected as 00:09:4c:xx:xx:xx (Communication Weaver Co.,Ltd.).
[01:51:56] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
[01:51:57] [mod.stopped] net.probe

[01:51:57] [sys.log] [inf] loading proxy script http-req-dump.js ...
[01:51:57] [sys.log] [dbg] Proxy script http-req-dump.js loaded.
[01:51:57] [sys.log] [inf] Enabling forwarding.
[01:51:57] [sys.log] [dbg] Applied redirection [en0] (TCP) :80 -> 192.168.1.122:8080
[01:51:57] [mod.started] http.proxy
[01:51:57] [sys.log] [inf] http.proxy started on 192.168.1.122:8080 (sslstrip disabled)
[01:51:57] [sys.log] [inf] loading proxy certification authority TLS key from /var/root/.bettercap-ca.key.pem
[01:51:57] [sys.log] [inf] loading proxy certification authority TLS certificate from /var/root/.bettercap-ca.cert.pem
[01:51:57] [sys.log] [inf] loading proxy script http-req-dump.js ...
[01:51:57] [sys.log] [dbg] Proxy script http-req-dump.js loaded.
[01:51:57] [sys.log] [inf] Enabling forwarding.
[01:51:57] [sys.log] [dbg] Applied redirection [en0] (TCP) :443 -> 192.168.1.122:8083
[01:51:57] [mod.started] https.proxy
[01:51:57] [sys.log] [inf] https.proxy started on 192.168.1.122:8083 (sslstrip disabled)
[01:51:57] [sys.log] [dbg]  addresses=[192.168.1.121] macs=[] whitelisted-addresses=[] whitelisted-macs=[]
[01:51:57] [sys.log] [inf] Enabling forwarding.
[01:51:57] [mod.started] arp.spoof
[01:51:57] [sys.log] [inf] ARP spoofer started, probing 1 targets.
192.168.1.0/24 > 192.168.1.122  » [01:51:57] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.121:78:4f:43:xx:xx:xx.
192.168.1.0/24 > 192.168.1.122  » [01:51:58] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.121:78:4f:43:xx:xx:xx.
...
...
```

_Thanks for this awesome tool_ ❤️

**Comment by evilsocket** [comment]
may i have the `netstat -nr` of that machine please? :)

**Comment by mgp25** [comment]
Sure, here it is:

```
mgp25@mbp:~$ netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc          146        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              2    24401     lo0
169.254            link#5             UCS             0        0     en0      !
192.168.1          link#5             UCS             2        0     en0      !
192.168.1.1/32     link#5             UCS             3        0     en0      !
192.168.1.1        ec:f4:51:xx:xx:xx  UHLWIir        72      190     en0   1199
192.168.1.83       14:5a:5:xx:xx:xx   UHLWI           0        0     en0    471
192.168.1.121      78:4f:43:xx:xx:xx   UHLWIi          1      110     en0   1151
192.168.1.122/32   link#5             UCS             0        0     en0      !
224.0.0/4          link#5             UmCS            1        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !
```

**Comment by evilsocket** [comment]
may i also have a `get *` output from inside bettercap?

**Comment by mgp25** [comment]
There is a file that requires one line to be added in order to support your functions:

```bash
diff --git a/firewall/firewall_darwin.go b/firewall/firewall_darwin.go
old mode 100644
new mode 100755
index bafde0f..0bffcb7
--- a/firewall/firewall_darwin.go
+++ b/firewall/firewall_darwin.go
@@ -9,6 +9,7 @@ import (
        "regexp"
        "strings"

+       "github.com/evilsocket/islazy/str"
        "github.com/bettercap/bettercap/core"
        "github.com/bettercap/bettercap/network"
 )
```

Also I found the following error when compiling:

```bash
make build && sudo make install
# github.com/bettercap/bettercap/vendor/github.com/google/gopacket/pcapgo
vendor/github.com/google/gopacket/pcapgo/capture.go:46:38: undefined: syscall.ETH_P_ALL
make: *** [build] Error 2
```

This is not a _Bettercap_ issue but a [gopacket](https://github.com/google/gopacket) which was addressed and patched a couple days ago in https://github.com/google/gopacket/pull/521 so getting latest code of it fixes it.

```
192.168.1.0/24 > 192.168.1.122  » get *


                                           $: '{by}{fw}{cidr} {fb}> {env.iface.ipv4} {reset} {bold}» {reset}'

                       any.proxy.dst_address: '<interface address>'
                          any.proxy.dst_port: '8080'
                             any.proxy.iface: '<interface name>'
                          any.proxy.protocol: 'TCP'
                       any.proxy.src_address: ''
                          any.proxy.src_port: '80'

                            api.rest.address: '<interface address>'
                        api.rest.alloworigin: '*'
                        api.rest.certificate: ''
                   api.rest.certificate.bits: '4096'
             api.rest.certificate.commonname: 'bettercap'
                api.rest.certificate.country: 'US'
               api.rest.certificate.locality: ''
           api.rest.certificate.organization: 'bettercap devteam'
     api.rest.certificate.organizationalunit: 'https://bettercap.org/'
                                api.rest.key: ''
                           api.rest.password: ''
                               api.rest.port: '8081'
                           api.rest.username: ''
                          api.rest.websocket: 'false'

                          arp.spoof.internal: 'false'
                           arp.spoof.targets: '<entire subnet>'
                         arp.spoof.whitelist: ''

                         dhcp6.spoof.domains: 'microsoft.com, google.com, facebook.com, apple.com, twitter.com'

                           dns.spoof.address: '<interface address>'
                               dns.spoof.all: 'false'
                           dns.spoof.domains: ''
                             dns.spoof.hosts: ''

             events.stream.http.request.dump: 'false'
            events.stream.http.response.dump: 'false'
                        events.stream.output: ''

                             gateway.address: '192.168.1.122'
                                 gateway.mac: '6c:40:08:xx:xx:xx'

                                gps.baudrate: '19200'
                                  gps.device: '/dev/ttyUSB0'

                                   http.port: '80'
                          http.proxy.address: '<interface address>'
                         http.proxy.injectjs: ''
                             http.proxy.port: '8080'
                           http.proxy.script: ''
                         http.proxy.sslstrip: 'false'
                         http.server.address: '<interface address>'
                     http.server.certificate: ''
                http.server.certificate.bits: '4096'
          http.server.certificate.commonname: 'bettercap'
             http.server.certificate.country: 'US'
            http.server.certificate.locality: ''
        http.server.certificate.organization: 'bettercap devteam'
  http.server.certificate.organizationalunit: 'https://bettercap.org/'
                             http.server.key: ''
                            http.server.path: '.'
                            http.server.port: '80'

                                  https.port: '443'
                         https.proxy.address: '<interface address>'
                     https.proxy.certificate: '~/.bettercap-ca.cert.pem'
                https.proxy.certificate.bits: '4096'
          https.proxy.certificate.commonname: 'Go Daddy Secure Certificate Authority - G2'
             https.proxy.certificate.country: 'US'
            https.proxy.certificate.locality: 'Scottsdale'
        https.proxy.certificate.organization: 'GoDaddy.com, Inc.'
  https.proxy.certificate.organizationalunit: 'https://certs.godaddy.com/repository/'
                        https.proxy.injectjs: ''
                             https.proxy.key: '~/.bettercap-ca.key.pem'
                            https.proxy.port: '8083'
                          https.proxy.script: ''
                        https.proxy.sslstrip: 'false'

                                 iface.index: '5'
                                  iface.ipv4: '192.168.1.122'
                                  iface.ipv6: 'fe80::186c:xxxx:xxxx:xxxx'
                                   iface.mac: '6c:40:08:xx:xx:xx'
                                  iface.name: 'en0'

                                   log.debug: 'false'
                                  log.silent: 'false'

                         mac.changer.address: '<random mac>'
                           mac.changer.iface: '<interface name>'

                        mysql.server.address: '<interface address>'
                         mysql.server.infile: '/etc/passwd'
                        mysql.server.outfile: ''
                           mysql.server.port: '3306'

                              net.probe.mdns: 'true'
                              net.probe.nbns: 'true'
                          net.probe.throttle: '10'
                              net.probe.upnp: 'true'
                               net.probe.wsd: 'true'
                               net.show.meta: 'true'
                            net.sniff.filter: 'not arp'
                             net.sniff.local: 'false'
                            net.sniff.output: ''
                            net.sniff.regexp: ''
                            net.sniff.source: ''
                           net.sniff.verbose: 'false'

                                 tcp.address: ''
                                    tcp.port: '443'
                           tcp.proxy.address: '<interface address>'
                              tcp.proxy.port: '8443'
                            tcp.proxy.script: ''
                          tcp.tunnel.address: ''
                             tcp.tunnel.port: '0'

                             ticker.commands: 'clear; net.show; events.show 20'
                               ticker.period: '1'

                               wifi.ap.bssid: '<random mac>'
                             wifi.ap.channel: '1'
                          wifi.ap.encryption: 'true'
                                wifi.ap.ssid: 'FreeWiFi'
                             wifi.hop.period: '250'
                            wifi.skip-broken: 'true'
                            wifi.source.file: ''
```

```
mgp25@mbp:~$ sudo bettercap -debug -caplet http-req-dump.cap -eval "set arp.spoof.targets 192.168.1.121"
bettercap v2.10 (type 'help' for a list of commands)

[17:01:49] [mod.started] net.recon
[17:01:49] [sys.log] [war] Could not detect gateway.
[17:01:49] [sys.log] [dbg] Throttling packets of 10 ms.
[17:01:49] [mod.started] events.stream
[17:01:49] [mod.started] net.probe
[17:01:49] [sys.log] [dbg] Throttling packets of 10 ms.
[17:01:49] [mod.started] net.probe
[17:01:49] [sys.log] [dbg] sent 88 bytes of MDNS probe
[17:01:49] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
[17:01:49] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
[17:01:49] [endpoint.new] endpoint 192.168.1.55 detected as 00:09:4c:xx:xx:xx (Communication Weaver Co.,Ltd.).
[17:01:49] [endpoint.new] endpoint 192.168.1.83 detected as 14:5a:05:xx:xx:xx (Apple, Inc.).
[17:01:50] [mod.stopped] net.probe


[17:01:50] [sys.log] [inf] loading proxy script http-req-dump.js ...
[17:01:50] [sys.log] [dbg] Proxy script http-req-dump.js loaded.
[17:01:50] [sys.log] [inf] Enabling forwarding.
[17:01:50] [sys.log] [dbg] Applied redirection [en0] (TCP) :80 -> 192.168.1.122:8080
[17:01:50] [mod.started] http.proxy
[17:01:50] [sys.log] [inf] http.proxy started on 192.168.1.122:8080 (sslstrip disabled)
[17:01:50] [sys.log] [inf] loading proxy certification authority TLS key from /var/root/.bettercap-ca.key.pem
[17:01:50] [sys.log] [inf] loading proxy certification authority TLS certificate from /var/root/.bettercap-ca.cert.pem
[17:01:50] [sys.log] [inf] loading proxy script http-req-dump.js ...
[17:01:50] [sys.log] [dbg] Proxy script http-req-dump.js loaded.
[17:01:50] [sys.log] [inf] Enabling forwarding.
[17:01:50] [sys.log] [dbg] Applied redirection [en0] (TCP) :443 -> 192.168.1.122:8083
[17:01:50] [mod.started] https.proxy
[17:01:50] [sys.log] [inf] https.proxy started on 192.168.1.122:8083 (sslstrip disabled)
[17:01:50] [sys.log] [dbg]  addresses=[192.168.1.121] macs=[] whitelisted-addresses=[] whitelisted-macs=[]
[17:01:50] [sys.log] [inf] Enabling forwarding.
[17:01:50] [mod.started] arp.spoof
[17:01:50] [sys.log] [inf] ARP spoofer started, probing 1 targets.
192.168.1.0/24 > 192.168.1.122  » [17:01:50] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.121:78:4f:43:xx:xx:xx.
```

I am not seeing the debug messages you have added :/  Let me know if you need anything more.

**Comment by evilsocket** [comment]
first of all thanks for debugging the compilation issues on macOS, just pushed a couple of fixes for that :D secondly, you should see something like:

![schermata da 2018-10-12 18-12-36](https://user-images.githubusercontent.com/86922/46880977-7e7fb300-ce4a-11e8-85cc-11d867899fcc.png)

Did you `sudo make install` before using `bettercap` without a path? :)

**Comment by mgp25** [comment]
Yup, totally my fault 😅 Now this is the good one:

```
mgp25@mbp:~$ sudo bettercap -debug
Password:
bettercap v2.10 (type 'help' for a list of commands)

[18:16:34] [sys.log] [dbg] FindGateway(en0) [cmd=netstat opts=[-n -r] parser=^([a-z]+)+\s+(\d+\.+\d+.\d.+\d)+\s+([a-zA-z]+)+\s+(\d+)+\s+(\d+)+\s+([a-zA-Z]+\d+)$]
[18:16:34] [sys.log] [dbg] FindGateway(en0) output:
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           99        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              2    75494     lo0
169.254            link#5             UCS             0        0     en0      !
192.168.1          link#5             UCS             1        0     en0      !
192.168.1.1/32     link#5             UCS             1        0     en0      !
192.168.1.1        ec:f4:51:xx:xx:xx  UHLWIir        38      457     en0   1197
192.168.1.121      78:4f:43:xx:xx:xx   UHLWIi          3      114     en0    493
192.168.1.122/32   link#5             UCS             0        0     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0        8     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#5                          UCI             en0
fe80::8a4:f672:c8fa:78a3%en0            78:4f:43:xx:xx:xx                UHLWIi          en0
fe80::186c:785:5c26:8857%en0            6c:40:8:xx:xx:xx                UHLI            lo0
fe80::%awdl0/64                         link#7                          UCI           awdl0
fe80::2029:abff:feea:177c%awdl0         22:29:ab:xx:xx:xx               UHLI            lo0
fe80::%utun0/64                         fe80::c7ff:7077:be70:6e74%utun0 UcI           utun0
fe80::c7ff:7077:be70:6e74%utun0         link#11                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#5                          UmCI            en0
ff01::%awdl0/32                         link#7                          UmCI          awdl0
ff01::%utun0/32                         fe80::c7ff:7077:be70:6e74%utun0 UmCI          utun0
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#5                          UmCI            en0
ff02::%awdl0/32                         link#7                          UmCI          awdl0
ff02::%utun0/32                         fe80::c7ff:7077:be70:6e74%utun0 UmCI          utun0
[18:16:34] [mod.started] net.recon
[18:16:34] [session.started] {session.started 2018-10-12 18:16:34.141103 +0200 CEST m=+0.030719769 <nil>}
[18:16:34] [mod.started] events.stream
[18:16:34] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.122  » [18:16:34] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
192.168.1.0/24 > 192.168.1.122  » [18:16:34] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
192.168.1.0/24 > 192.168.1.122  »
```

**Comment by evilsocket** [comment]
it seems now it's working?

**Comment by mgp25** [comment]
Partially. I can't tell why yet, but sometimes it seems to be working fine (Warning message gone), and sometimes it appears:

**First run (fails):**

```
mgp25@mbp:~$ sudo bettercap -debug
bettercap v2.10 (type 'help' for a list of commands)

[18:32:52] [sys.log] [dbg] FindGateway(en0) [cmd=netstat opts=[-n -r] parser=^([a-z]+)+\s+(\d+\.+\d+.\d.+\d)+\s+([a-zA-z]+)+\s+(\d+)+\s+(\d+)+\s+([a-zA-Z]+\d+)$]
[18:32:52] [sys.log] [war] Could not detect gateway.
[18:32:52] [mod.started] net.recon
[18:32:52] [session.started] {session.started 2018-10-12 18:32:52.601813 +0200 CEST m=+0.030035821 <nil>}
192.168.1.0/24 > 192.168.1.122  » [18:32:52] [mod.started] events.stream
[18:32:52] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.122  » [18:32:52] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
192.168.1.0/24 > 192.168.1.122  » [18:32:52] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
192.168.1.0/24 > 192.168.1.122  » [18:32:52] [endpoint.new] endpoint 192.168.1.55 detected as 00:09:4c:xx:xx:xx (Communication Weaver Co.,Ltd.).
192.168.1.0/24 > 192.168.1.122  » q
[18:32:57] [mod.stopped] events.stream
```

**Second run (works):**

```
mgp25@mbp:~$ sudo ./bettercap -debug
bettercap v2.10 (type 'help' for a list of commands)

[18:33:19] [sys.log] [dbg] FindGateway(en0) [cmd=netstat opts=[-n -r] parser=^([a-z]+)+\s+(\d+\.+\d+.\d.+\d)+\s+([a-zA-z]+)+\s+(\d+)+\s+(\d+)+\s+([a-zA-Z]+\d+)$]
[18:33:19] [sys.log] [dbg] FindGateway(en0) output:
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           95        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              2    75494     lo0
169.254            link#5             UCS             0        0     en0      !
192.168.1          link#5             UCS             2        0     en0      !
192.168.1.1/32     link#5             UCS             1        0     en0      !
192.168.1.1        ec:f4:51:xx:xx:xx  UHLWIir        32      596     en0   1170
192.168.1.55       0:9:4c:xx:xx:xx     UHLWI           0        5     en0   1027
192.168.1.121      78:4f:43:xx:xx:xx   UHLWIi          3      134     en0   1139
192.168.1.122/32   link#5             UCS             0        0     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0       21     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !

Internet6:
...
...
[18:33:19] [mod.started] net.recon
[18:33:19] [session.started] {session.started 2018-10-12 18:33:19.246405 +0200 CEST m=+0.031615601 <nil>}
```

**Fourth run (fails):**

```
mgp25@mbp:~$ sudo bettercap -debug
bettercap v2.10 (type 'help' for a list of commands)

192.168.1.0/24 > 192.168.1.122  » [18:35:57] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [sys.log] [dbg] FindGateway(en0) [cmd=netstat opts=[-n -r] parser=^([a-z]+)+\s+(\d+\.+\d+.\d.+\d)+\s+([a-zA-z]+)+\s+(\d+)+\s+(\d+)+\s+([a-zA-Z]+\d+)$]
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [sys.log] [dbg] FindGateway(en0) output:
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           92        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              2    75494     lo0
169.254            link#5             UCS             0        0     en0      !
192.168.1          link#5             UCS             1        0     en0      !
192.168.1.1/32     link#5             UCS             2        0     en0      !
192.168.1.1        ec:f4:51:xx:xx:xx  UHLWIir        20        0     en0   1175
192.168.1.121      78:4f:43:xx:xx:xx   UHLWIi          2        3     en0   1071
192.168.1.122/32   link#5             UCS             0        0     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0       21     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !

Internet6:
...
...
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [sys.log] [war] Could not detect gateway.
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [session.started] {session.started 2018-10-12 18:35:57.058332 +0200 CEST m=+0.031358102 <nil>}
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [mod.started] events.stream
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [mod.started] net.recon
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
192.168.1.0/24 > 192.168.1.122  » [18:35:57] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
```

Yet still, when running (and no warning message):

```
mgp25@mbp:~$ sudo bettercap -debug -caplet http-req-dump.cap -eval "set arp.spoof.targets 192.168.1.121"
bettercap v2.10 (type 'help' for a list of commands)

[18:38:37] [mod.started] net.recon
[18:38:37] [sys.log] [dbg] FindGateway(en0) output:
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc           94        0     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              2    75494     lo0
169.254            link#5             UCS             0        0     en0      !
192.168.1          link#5             UCS             1        0     en0      !
192.168.1.1/32     link#5             UCS             2        0     en0      !
192.168.1.1        ec:f4:51:xx:xx:xx  UHLWIir        25       10     en0   1158
192.168.1.121      78:4f:43:3:bf:75   UHLWIi          2       12     en0   1112
192.168.1.122/32   link#5             UCS             0        0     en0      !
224.0.0/4          link#5             UmCS            2        0     en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0       21     en0
255.255.255.255/32 link#5             UCS             0        0     en0      !

Internet6:
...
...
...
[18:38:37] [sys.log] [dbg] Throttling packets of 10 ms.
[18:38:37] [session.started] {session.started 2018-10-12 18:38:37.351899 +0200 CEST m=+0.032569836 <nil>}
[18:38:37] [mod.started] net.probe
[18:38:37] [mod.started] net.recon
[18:38:37] [sys.log] [dbg] Throttling packets of 10 ms.
[18:38:37] [mod.started] net.probe
[18:38:37] [sys.log] [dbg] sent 88 bytes of MDNS probe
[18:38:37] [endpoint.new] endpoint 192.168.1.1 detected as ec:f4:51:xx:xx:xx (Arcadyan Corporation).
[18:38:37] [endpoint.new] endpoint 192.168.1.121 detected as 78:4f:43:xx:xx:xx (Apple, Inc.).
[18:38:38] [endpoint.new] endpoint 192.168.1.55 detected as 00:09:4c:xx:xx:xx (Communication Weaver Co.,Ltd.).
[18:38:38] [mod.stopped] net.probe


[18:38:38] [sys.log] [inf] loading proxy script http-req-dump.js ...
[18:38:38] [sys.log] [dbg] Proxy script http-req-dump.js loaded.
[18:38:38] [sys.log] [inf] Enabling forwarding.
[18:38:38] [sys.log] [dbg] Applied redirection [en0] (TCP) :80 -> 192.168.1.122:8080
[18:38:38] [mod.started] http.proxy
[18:38:38] [sys.log] [inf] http.proxy started on 192.168.1.122:8080 (sslstrip disabled)
[18:38:38] [sys.log] [inf] loading proxy certification authority TLS key from /var/root/.bettercap-ca.key.pem
[18:38:38] [sys.log] [inf] loading proxy certification authority TLS certificate from /var/root/.bettercap-ca.cert.pem
[18:38:38] [sys.log] [inf] loading proxy script http-req-dump.js ...
[18:38:38] [sys.log] [dbg] Proxy script http-req-dump.js loaded.
[18:38:38] [sys.log] [inf] Enabling forwarding.
[18:38:38] [sys.log] [dbg] Applied redirection [en0] (TCP) :443 -> 192.168.1.122:8083
[18:38:38] [mod.started] https.proxy
[18:38:38] [sys.log] [inf] https.proxy started on 192.168.1.122:8083 (sslstrip disabled)
[18:38:38] [sys.log] [dbg]  addresses=[192.168.1.121] macs=[] whitelisted-addresses=[] whitelisted-macs=[]
[18:38:38] [sys.log] [inf] Enabling forwarding.
[18:38:38] [mod.started] arp.spoof
[18:38:38] [sys.log] [inf] ARP spoofer started, probing 1 targets.
192.168.1.0/24 > 192.168.1.122  » [18:38:38] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.121:78:4f:43:xx:xx:xx.
192.168.1.0/24 > 192.168.1.122  » [18:38:39] [sys.log] [dbg] Sending 60 bytes of ARP packet to 192.168.1.121:78:4f:43:xx:xx:xx.
```

I am not able to get any spoofed requests shown there

**Comment by evilsocket** [comment]
this is very very *very* weird, i added more debug logs to understand wtf is going on, when you have time please pull, make build && sudo make install ... thanks a ton for your help!!!

**Comment by mgp25** [comment]
No worries, I am glad to be able to help on this.

I applied your changes but it would keep failing. Some minutes ago I started debuging in order to find the root of the issue. I debugged this part:

```go
	ifName := iface.Name()
	for _, line := range strings.Split(output, "\n") {
		if strings.Contains(line, ifName) {
			m := IPv4RouteParser.FindStringSubmatch(line)
			if len(m) == IPv4RouteTokens {
```

And each time it was printing the line correctly, as it supposed to do:

```
OOOOO(Routing tables)
OOOOO()
OOOOO(Internet:)
OOOOO(Destination        Gateway            Flags        Refs      Use   Netif Expire)
OOOOO(default            192.168.1.1        UGSc           96        0     en0       )
OOOOO(169.254            link#5             UCS             0        0     en0      !)
OOOOO(192.168.1.1/32     link#5             UCS             1        0     en0      !)
```

Don't mind the `OOOOO`, it was a tag to find things easily while chcking the terminal. Maybe by now you have realized what was the issue:

https://github.com/bettercap/bettercap/blob/236a9940d9f3822261592e24cd693315c9171349/network/net_darwin.go#L13

Since there are extra spaces at the end, the regexp couln't match the string since it asked for a word. After removing just the `$` of the regexp, I started seeing your debug messages:

```
[01:44:34] [sys.log] [dbg] FindGateway(en0) line 'default            192.168.1.1        UGSc           98        0     en0       ' matched with [default            192.168.1.1        UGSc           98        0     en0 default 192.168.1.1 UGSc 98 0 en0]
[01:44:34] [sys.log] [dbg] gateway is 192.168.1.1[ec:f4:51:a2:6a:7f]
[01:44:34] [session.started] {session.started 2018-10-13 01:44:34.021382 +0200 CEST m=+0.040295613 <nil>}
[01:44:34] [mod.started] events.stream
[01:44:34] [mod.started] net.recon
```

Another solution, that works without changing the regexp would be to trim the line. I don't know if this is the most elegant way to do it:

```go
diff --git a/network/net_gateway.go b/network/net_gateway.go
index c3daa99..d63257d 100644
--- a/network/net_gateway.go
+++ b/network/net_gateway.go
@@ -21,6 +21,7 @@ func FindGateway(iface *Endpoint) (*Endpoint, error) {

        ifName := iface.Name()
        for _, line := range strings.Split(output, "\n") {
+               line := strings.Trim(line, " ")
                if strings.Contains(line, ifName) {
                        m := IPv4RouteParser.FindStringSubmatch(line)
                        if len(m) == IPv4RouteTokens {
```

After this changes are applied, arp spoofing and other features started to work again!! 😄😄 

```
[02:06:38] [http.proxy.spoofed-request] {http.proxy.spoofed-request 2018-10-13 02:06:38.926651 +0200 CEST m=+24.313271251 {192.168.1.121 GET www.mgp25.com / 0}}
192.168.1.0/24 > 192.168.1.122  » [02:06:39] [sys.log] [dbg] (http.proxy) >  GET www.mgp25.com/
192.168.1.0/24 > 192.168.1.122  » [02:06:39] [sys.log] [dbg] (http.proxy) < 192.168.1.121:55378 GET mgp25.com/
192.168.1.0/24 > 192.168.1.122  » [02:06:39] [sys.log] [inf] [http-req-dump] http 192.168.1.121 GET http://mgp25.com/
192.168.1.0/24 > 192.168.1.122  »
  Headers
...
...
...
```

If you ever need anyone to test any feature in macOS, ping me, I'll be glad to test it.

Have a nice weekend! 🍺

**Comment by evilsocket** [comment]
dude you're the best! :D thanks again

**Comment by g4z** [comment]
Hi

*Not sure whether i should create a new ticket for this. I'll post it here as it may help someone else who searched for "Could not detect gateway" as i did!*

I have a similar issue whereby bettercap cannot determine the gateway address based on the output (in my case) of the `ip route` command.

I'm using a Debian 9.5 based OS: `bone-debian-9.5-iot-armhf-2018-10-07-4gb.img.xz`

```
debian@beaglebone:~$ uname -a
Linux beaglebone 4.14.71-ti-r80 #1 SMP PREEMPT Fri Oct 5 23:50:11 UTC 2018 armv7l GNU/Linux

debian@beaglebone:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
<snip>

debian@beaglebone:~$ ip route
default via 192.168.10.1 dev eth0
192.168.10.0/24 dev eth0 proto kernel scope link src 192.168.10.134
192.168.10.1 dev eth0 scope link

debian@beaglebone:~$ unzip bettercap_linux_arm7_2.11.zip
Archive:  bettercap_linux_arm7_2.11.zip
  inflating: bettercap
  inflating: README.md
  inflating: LICENSE.md

debian@beaglebone:~$ sudo ./bettercap -debug
bettercap v2.11 (type 'help' for a list of commands)

192.168.10.0/24 > 192.168.10.134  » [17:55:34] [sys.log] [dbg] FindGateway(eth0) [cmd=ip opts=[route] parser=^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s(\w+)\s.*$]
192.168.10.0/24 > 192.168.10.134  » [17:55:34] [sys.log] [dbg] FindGateway(eth0) output:
default via 192.168.10.1 dev eth0
192.168.10.0/24 dev eth0 proto kernel scope link src 192.168.10.134
192.168.10.1 dev eth0 scope link
192.168.10.0/24 > 192.168.10.134  » [17:55:34] [sys.log] [dbg] FindGateway(eth0): nothing found :/
192.168.10.0/24 > 192.168.10.134  » [17:55:34] [sys.log] [war] Could not detect gateway.
...
<snip>
```

It works if apply the following change...

```
diff --git a/network/net_linux.go b/network/net_linux.go
index decbc02..d7c3930 100644
--- a/network/net_linux.go
+++ b/network/net_linux.go
@@ -13,7 +13,7 @@ import (
 )

 // only matches gateway lines
-var IPv4RouteParser = regexp.MustCompile(`^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s(\w+)\s.*$`)
+var IPv4RouteParser = regexp.MustCompile(`^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s(\w+)[\s\w]*$`)
 var IPv4RouteTokens = 4
 var IPv4RouteCmd = "ip"
 var IPv4RouteCmdOpts = []string{"route"}
```

Works ok with this change...

```
debian@beaglebone:~$ sudo ./bettercap -debug
bettercap v2.11 (type 'help' for a list of commands)

192.168.10.0/24 > 192.168.10.134  » [18:18:34] [sys.log] [dbg] FindGateway(eth0) [cmd=ip opts=[route] parser=^(default|[0-9\.]+)\svia\s([0-9\.]+)\sdev\s(\w+)[\s\w]*$]
192.168.10.0/24 > 192.168.10.134  » [18:18:34] [sys.log] [dbg] FindGateway(eth0) output:
default via 192.168.10.1 dev eth0
192.168.10.0/24 dev eth0 proto kernel scope link src 192.168.10.134
192.168.10.1 dev eth0 scope link
192.168.10.0/24 > 192.168.10.134  » [18:18:34] [sys.log] [dbg] gateway is 192.168.10.1[00:08:a2:xx:xx:xx]
...
<snip>

```

Is this something that could be merged or fixed another way?

**Comment by g4z** [comment]
now i see that this was fixed 2 days ago... and i hadn't pulled the latest code for 3 days :)

this issue i mentioned above was fixed here: https://github.com/bettercap/bettercap/commit/47c37c066ca178f304809964b138ff0afb871722

thanks

**Comment by pthreat** [comment]
Instead of trying to magically detect the gateway add an option so the gateway can be specified. Just a humble opinion. Yes, I'm having exactly the same problem

**Comment by harshanand120** [comment]
i m still having this issue with bettercap 2.26.1 on macos catalina

**Comment by Drjacky** [comment]
Same issue on v2.24.1:
```bash
➜  bettercap_scripts sudo bettercap -debug
bettercap v2.24.1 (built for darwin arm64 with go1.20.4) [type 'help' for a list of commands]

127.0.0.0/8 > 127.94.0.1  » [11:17:01] [sys.log] [dbg] FindGateway(lo0) [cmd=netstat opts=[-n -r] parser=^([a-z]+)+\s+(\d+\.+\d+.\d.+\d)+\s+([a-zA-z]+)+\s+(\d+)+\s+(\d+)+\s+([a-zA-Z]+\d+)$]
127.0.0.0/8 > 127.94.0.1  » [11:17:01] [sys.log] [dbg] FindGateway(lo0) output:
Routing tables

Internet:
Destination        Gateway            Flags           Netif Expire
default            link#26            UCSg            utun3
3.225.43.49        link#26            UHWIig          utun3
3.230.47.108       link#26            UHWIig          utun3
8.8.8.8            link#26            UHW3Ig          utun3    358
10.8.1.2           10.8.1.2           UH              utun3
10.8.1.255         link#26            UHW3Ig          utun3    390
17.57.146.13       link#26            UHWIig          utun3
17.248.238.64      link#26            UHW3Ig          utun3    439
23.200.147.24      link#26            UHW3Ig          utun3    383
34.160.120.42      link#26            UHWIig          utun3
52.214.37.149      link#26            UHWIig          utun3
74.125.193.94      link#26            UHWIig          utun3
74.125.193.95      link#26            UHWIig          utun3
74.125.193.139     link#26            UHWIig          utun3
74.125.193.190     link#26            UHW3Ig          utun3    428
92.38.148.17       link#26            UHWIig          utun3
103.86.99.99       link#26            UHWIig          utun3
108.177.122.94     link#26            UHWIig          utun3
127                127.0.0.1          UCS               lo0
127.0.0.1          127.0.0.1          UH                lo0
127.94.0.1         127.94.0.1         UH                lo0
140.82.112.25      link#26            UHWIig          utun3
158.101.44.242     link#26            UHW3Ig          utun3    350
169.254            link#15            UCS               en0      !
......
192.0.0.88         link#26            UHW3Ig          utun3    470
192.168.0          link#15            UCS               en0      !
192.168.0.1/32     link#15            UCS               en0      !
192.168.0.1        cc:58:30:ec:62:85  UHLWIir           en0   1139
192.168.0.25       fa:de:69:98:cc:3c  UHLWIi            en0    566
192.168.0.46/32    link#15            UCS               en0      !
192.168.0.46       5c:e9:1e:c3:78:de  UHLWI             lo0
192.168.0.48       b0:e4:d5:ee:2a:c2  UHLWIi            en0    553
192.168.0.255      ff:ff:ff:ff:ff:ff  UHLWbI            en0      !
203.10.96.34       link#26            UHW3Ig          utun3    459
217.138.222.203    192.168.0.1        UGHS              en0
224.0.0/4          link#26            UmCS            utun3
224.0.0/4          link#15            UmCSI             en0      !
224.0.0.251        1:0:5e:0:0:fb      UHmLWI            en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI            en0
239.255.255.250    link#26            UHmW3I          utun3    473
255.255.255.255/32 link#26            UCS             utun3
255.255.255.255/32 link#15            UCSI              en0      !

Internet6:
Destination                             Gateway                         Flags           Netif Expire
default                                 fe80::%utun0                    UGcIg           utun0
default                                 fe80::%utun1                    UGcIg           utun1
default                                 fe80::%utun2                    UGcIg           utun2
default                                 fe80::%utun4                    UGcIg           utun4
default                                 fe80::%utun5                    UGcIg           utun5
::1                                     ::1                             UHL               lo0
...........
127.0.0.0/8 > 127.94.0.1  » [11:17:01] [sys.log] [dbg] FindGateway(lo0): nothing found :/
127.0.0.0/8 > 127.94.0.1  » [11:17:01] [sys.log] [war] Could not detect gateway.
127.0.0.0/8 > 127.94.0.1  » [11:17:01] [session.started] {session.started 2023-09-24 11:17:01.413036 +0100 IST m=+0.024812459 <nil>}
127.0.0.0/8 > 127.94.0.1  » [11:17:01] [mod.started] events.stream
```
@evilsocket 

it was working with the first run. then I forced closed it in the command by pressing command + C
