### ISSUE TITLE
Caplet Download-Autopwn Bug

### ISSUE THREAD

**Issue by HennyestHenry** [bettercap/bettercap#683]
### Description of the bug
When using the caplet Download-Autopwn it works well on all the file types ive tried however when the victim(me) tries to download a exe file to a windows os from a http site, the bettercap terminal on the attackers machine (also me) goes crazy and displays 

> Autopwning download request from (victim)

about 5-7 times always with changing requested file sizes, and on the victim's machine the download is either marked as incomplete or there was a network error, either way the served exe is never in a execute-able state and never even made it onto the the victims pc.

### Environment
Kali Linux Virtual Box 

* Bettercap version - 2.26.1
* OS version - Kali GNU/Linux Rolling Linux version 5.3.0-kali3-amd64
* Go version - go1.13.5
* Caplet code hasnt been changed 

 ### Full debug output

```
`root@kali:~# bettercap -debug`
` bettercap v2.26.1 (built for linux amd64 with go1.13.5) [type 'help' for a list of commands]`

`192.168.0.0/24 > 192.168.0.37  » [02:11:56] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]`

`192.168.0.0/24 > 192.168.0.37  » [02:11:56] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.0.1 dev wlan0 proto dhcp metric 600 `

`192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.37 metric 600`

`192.168.0.0/24 > 192.168.0.37  » [02:11:56] [sys.log] [dbg] FindGateway(wlan0) line 'default via
 192.168.0.1 dev wlan0 proto dhcp metric 600' matched with [default via 192.168.0.1 dev wlan0 proto dhcp metric 600 default 192.168.0.1 wlan0]`

`192.168.0.0/24 > 192.168.0.37  » [02:11:56] [sys.log] [dbg] gateway is 192.168.0.1[b1:bc:ed:c3:8h:69]`

`192.168.0.0/24 > 192.168.0.37  » [02:11:56] [session.started] {session.started 2020-01-08 02:11:56.752904042 +0000 GMT m=+0.053948065 <nil>}`

`192.168.0.0/24 > 192.168.0.37  » [02:11:56] [mod.started] events.stream`

`192.168.0.0/24 > 192.168.0.37  »`
```

### Steps to Reproduce
* install bettercap how instructed 
* open terminal and type bettercap
* type set arp.spoof.targets -victim-
* type arp.spoof on
* type download-autopwn/download-autopwn
* attempt to download exe file from a http site to a windows 10 OS

**Expected behavior:**
exe file to be replaced with payload successfully and for the exe payload to be functioning as intended 

**Actual behavior:** 
exe file could never be downloaded to victim

* i tried this with a .bat file and it worked 100% fine it was successfully replaced and the payload was functioning.
* i also tried with a .zip file, and the file was corrupted.
* have not tried with other file types as it is currently 2am and im tired.

**Comment by buffermet** [comment]
How large is the exe file?

I just pushed https://github.com/bettercap/caplets/commit/554c7c8d17b1111a82d8653a25d853c054163825 to prevent the response body from being read if a Content-Length header is set.

My guess is that there is latency causing the download to time out because the proxy script used to read every response body in order to resize your payload.

Closing for now, let us know if the problem persists.

**Comment by HennyestHenry** [comment]
[https://youtu.be/Yd_7qEH1J1I](url)
same issue still, still works with .bat files

**Comment by buffermet** [comment]
The issue appears to be the Content-Length header.

I believe this is because strings in Javascript are UTF-16, causing the browser to think that the file has a different byte size.

I managed to get around this issue by removing the Content-Length header. This means that the user won't see the size of the file before downloading it.
